### ISSUE TITLE
Tooltip not visible when grids are replaced with images

### ISSUE THREAD

**Issue by ComMouse** [dyweb/colorful-contribution#2]
When I was trying the theme "Mario", it seemed that the "tooltips" `(x contributions on xxx)` which would show when I move the mouse over the original grids are not visible now.

If possible, please help fix this problem. Thx.

Version: 0.2.0

**Comment by gigaflw** [comment]
Wow, you've got sharp eyes.
Fixed, thanks for mentioning! 👍
