### ISSUE TITLE
[bug] Little commits will not show up in the contribution graph

### ISSUE THREAD

**Issue by voldikss** [dyweb/colorful-contribution#5]
![13](https://user-images.githubusercontent.com/20282795/41504179-108e78b8-721a-11e8-8d2c-c300f1008ade.png)

While displayed with heavy green in the original GitHub contribution bar.

![11](https://user-images.githubusercontent.com/20282795/41504167-c9f1f6b4-7219-11e8-898d-98c976799810.png)

**Comment by gigaflw** [comment]
Fixed in v0.3.0
